### ISSUE TITLE
remove  appInfo method

### ISSUE THREAD

**Issue by mumiao** [DTStack/dt-utils#39]
![image](https://user-images.githubusercontent.com/22880945/134462289-c4ac9d3b-dfdd-4b02-840c-6477dbcedcdd.png)

**Comment by liuxy0551** [comment]
已发布 v1.0.6  
内网：http://registry.npm.dtstack.com/-/web/detail/@dtinsight/dt-utils  
公网：https://www.npmjs.com/package/@dtinsight/dt-utils
