### ISSUE TITLE
v1.1.0 发布计划

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/dt-utils#57]
- #56 Base64 相关方法
 - #58 千分位支持传入 undefined、null，此时返回 '0'
 - #59  移除 toQfw 方法，优化 getThousandth

**Comment by liuxy0551** [comment]
已发布 v1.1.0

**Comment by mumiao** [comment]
发布后 UED同步一下 大版本更新 或者机器人通知一下 跟doremon一样  @liuxy0551
